use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

const DOMAIN: &str = "ankunft";

fn main() {
    println!("cargo:rerun-if-env-changed=MSGFMT");
    println!("cargo:rerun-if-env-changed=ANKUNFT_LOCALEDIR");

    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo did not provide CARGO_MANIFEST_DIR"),
    );
    let po_dir = manifest_dir.join("po");
    let linguas_path = po_dir.join("LINGUAS");
    println!("cargo:rerun-if-changed={}", linguas_path.display());

    let locales = read_linguas(&linguas_path);
    assert!(
        !locales.is_empty(),
        "po/LINGUAS does not contain any locales"
    );

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo did not provide OUT_DIR"));
    let locale_root = out_dir.join("locale");
    let msgfmt = env::var_os("MSGFMT").unwrap_or_else(|| "msgfmt".into());
    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         pub(crate) static EMBEDDED_CATALOGS: &[(&str, &[u8])] = &[\n",
    );

    for locale in locales {
        validate_locale(&locale);
        let source = po_dir.join(format!("{locale}.po"));
        println!("cargo:rerun-if-changed={}", source.display());
        assert!(
            source.is_file(),
            "missing translation catalog: {}",
            source.display()
        );

        let destination = locale_root
            .join(&locale)
            .join("LC_MESSAGES")
            .join(format!("{DOMAIN}.mo"));
        fs::create_dir_all(destination.parent().expect("MO destination has a parent"))
            .expect("could not create compiled locale directory");

        compile_catalog(&msgfmt, &source, &destination);
        generated.push_str(&format!(
            "    ({locale:?}, include_bytes!({path:?})),\n",
            path = destination.to_string_lossy(),
        ));
    }

    generated.push_str("];\n");
    fs::write(out_dir.join("ankunft_i18n_catalogs.rs"), generated)
        .expect("could not write generated catalog manifest");

    println!(
        "cargo:rustc-env=ANKUNFT_BUILD_LOCALE_DIR={}",
        locale_root.display()
    );
}

fn read_linguas(path: &Path) -> Vec<String> {
    let contents = fs::read_to_string(path).expect("could not read po/LINGUAS");
    contents
        .lines()
        .map(|line| line.split('#').next().unwrap_or_default())
        .flat_map(str::split_whitespace)
        .map(str::to_owned)
        .collect()
}

fn validate_locale(locale: &str) {
    assert!(
        !locale.is_empty()
            && locale != "."
            && locale != ".."
            && locale
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'@')),
        "invalid locale in po/LINGUAS: {locale:?}"
    );
}

fn compile_catalog(msgfmt: &std::ffi::OsStr, source: &Path, destination: &Path) {
    let status = Command::new(msgfmt)
        .arg("--check")
        .arg("--output-file")
        .arg(destination)
        .arg(source)
        .status()
        .unwrap_or_else(|error| {
            panic!("could not execute msgfmt ({error}); install GNU gettext or set MSGFMT")
        });

    assert!(status.success(), "msgfmt rejected {}", source.display());
}
